using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace PracticeASP
{
    public partial class ChechInfo : System.Web.UI.Page
    {

        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void GridView2_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        protected void SqlDataSource1_Selecting(object sender, SqlDataSourceSelectingEventArgs e)
        {

        }

        protected void ShowAdminPanelBtn_Click(object sender, EventArgs e)
        {
            ProductAdminPanel.Visible = true;
        }

        private void ClearAddProductsForm()
        {
            TextBoxTitle.Text = "";
            TextBoxPrice.Text = "";
        }

        protected void AddBtn_Click(object sender, EventArgs e)
        {
            SqlDataProducts.Insert();
            GridViewProducts.DataBind();
            ClearAddProductsForm();
        }

        protected void ClearBtn_Click(object sender, EventArgs e)
        {
            ClearAddProductsForm();
        }

        protected void ButtonUpdateProduct_Click(object sender, EventArgs e)
        {
            if (ButtonUpdateProduct.Text == "Изменить продукт")
            {
                ButtonUpdateProduct.Text = "Завершить редактирование";
                GridViewProducts.AutoGenerateEditButton = true;
            }
            else
            {
                ButtonUpdateProduct.Text = "Изменить продукт";
                GridViewProducts.AutoGenerateEditButton = false;
            }

        }

        protected void ButtonDeleteProduct_Click(object sender, EventArgs e)
        {
            if(ButtonDeleteProduct.Text == "Удалить")
            {
                ButtonDeleteProduct.Text = "Закончить удаление";
                GridViewProducts.AutoGenerateDeleteButton = true;
            }
            else
            {
                ButtonDeleteProduct.Text = "Удалить";
                GridViewProducts.AutoGenerateDeleteButton = false;
            }
        }

    }
}