using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace PracticeASP
{
    public partial class ChechInfo : System.Web.UI.Page
    {

        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void GridView2_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        protected void SqlDataSource1_Selecting(object sender, SqlDataSourceSelectingEventArgs e)
        {

        }

        protected void ShowAdminPanelBtn_Click(object sender, EventArgs e)
        {
            ProductAdminPanel.Visible = true;
        }

        private void ClearAddProductsForm()
        {
            TextBoxTitle.Text = "";
            TextBoxPrice.Text = "";
        }

        protected void AddBtn_Click(object sender, EventArgs e)
        {
            SqlDataProducts.Insert();
            GridViewProducts.DataBind();
            ClearAddProductsForm();
        }

        protected void ClearBtn_Click(object sender, EventArgs e)
        {
            ClearAddProductsForm();
        }

        protected void ButtonUpdateProduct_Click(object sender, EventArgs e)
        {
            if (ButtonUpdateProduct.Text == "Изменить продукт")
            {
                ButtonUpdateProduct.Text = "Завершить редактирование";
                GridViewProducts.AutoGenerateEditButton = true;
            }
            else
            {
                ButtonUpdateProduct.Text = "Изменить продукт";
                GridViewProducts.AutoGenerateEditButton = false;
            }

        }

        protected void ButtonDeleteProduct_Click(object sender, EventArgs e)
        {
            if(ButtonDeleteProduct.Text == "Удалить")
            {
                ButtonDeleteProduct.Text = "Закончить удаление";
                GridViewProducts.AutoGenerateDeleteButton = true;
            }
            else
            {
                ButtonDeleteProduct.Text = "Удалить";
                GridViewProducts.AutoGenerateDeleteButton = false;
            }
        }


        private void ClearAddCostumerForm()
        {
            TextBoxCostumerName.Text = "";
            TextBoxCostumerSurname.Text = "";
            TextBoxDateOdBorn.Text = "";
        }

        protected void ButtonShowCostumerAdmin_Click(object sender, EventArgs e)
        {
            PanelAdminCostumer.Visible = true;
        }

        protected void ButtonAddCostumer_Click(object sender, EventArgs e)
        {
            SqlDataCustomer.Insert();
            GridViewCustomer.DataBind();
            ClearAddCostumerForm();
        }

        protected void ButtonClearCostumerForm_Click(object sender, EventArgs e)
        {
            ClearAddCostumerForm();
        }

        protected void ButtonChangeCustomer_Click(object sender, EventArgs e)
        {
            if (ButtonChangeCustomer.Text == "Изменить покупателя")
            {
                ButtonChangeCustomer.Text = "Завершить редактирование";
                GridViewCustomer.AutoGenerateEditButton = true;
            }
            else
            {
                ButtonChangeCustomer.Text = "Изменить покупателя";
                GridViewCustomer.AutoGenerateEditButton = false;
            }
        }

        protected void ButtonDeleteCustomer_Click(object sender, EventArgs e)
        {
            if (ButtonDeleteCustomer.Text == "Удалить покупателя")
            {
                ButtonDeleteCustomer.Text = "Закончить удаление";
                GridViewCustomer.AutoGenerateDeleteButton = true;
            }
            else
            {
                ButtonDeleteCustomer.Text = "Удалить покупателя";
                GridViewCustomer.AutoGenerateDeleteButton = false;
            }
        }

        protected void ButtonOpenAdminOrder_Click(object sender, EventArgs e)
        {
            OrderAdminPanel.Visible = true;
        }


        private void ClearOrderForm()
        {
            TextBoxCustomerID.Text = "";
            TextBoxProductID.Text = "";
            TextBoxOrderComment.Text = "";
        }
        protected void ButtonAddOrder_Click(object sender, EventArgs e)
        {
            SqlDataOrders.Insert();
            GridViewOrders.DataBind();
            ClearOrderForm();
        }

        protected void ButtonClearOrderForm_Click(object sender, EventArgs e)
        {
            ClearOrderForm();
        }


        protected void ButtonUpdateOrder_Click(object sender, EventArgs e)
        {
            if (ButtonUpdateOrder.Text == "Изменить заказ")
            {
                ButtonUpdateOrder.Text = "Завершить редактирование";
                GridViewOrders.AutoGenerateEditButton = true;
            }
            else
            {
                ButtonUpdateOrder.Text = "Изменить заказ";
                GridViewOrders.AutoGenerateEditButton = false;
            }
        }

        protected void ButtonDeleteOrder_Click(object sender, EventArgs e)
        {
            if (ButtonDeleteOrder.Text == "Удалить заказ")
            {
                ButtonDeleteOrder.Text = "Закончить удаление";
                GridViewOrders.AutoGenerateDeleteButton = true;
            }
            else
            {
                ButtonDeleteOrder.Text = "Удалить заказ";
                GridViewOrders.AutoGenerateDeleteButton = false;
            }
        }
    }
}